name: even_number_checker
description: Practice defining functions with return types and using the return keyword in Dart.
version: 1.0.0

environment:
  sdk: ">=3.10.0 <4.0.0"

dev_dependencies:
  test: ^1.25.0

